name: check

on:
  push:
    branches:
      - main
      - rebuild/**
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install

      - name: Check
        run: pnpm check
